fun main() {
    print("Student Enrollment No.: ")
    var a = readLine()
    print("Student Name : ")
    var b = readLine()
    print("Student Branch : ")
    var c = readLine()
    print("Student Class : ")
    var d = readLine()
    print("Student Batch : ")
    var e = readLine()
    print("Student College Name : ")
    var f = readLine()
    print("Student University Name : ")
    var g = readLine()
    print("Student Age : ")
    var h = readLine()

    println("*********************************")

    println("Student's Data : ")
    println("Enrollment No. : "+a)
    println("Name : "+b)
    println("Age : "+h)
    println("Branch : "+c)
    println("Class : "+d)
    println("Batch : "+e)
    println("College Name : "+f)
    println("University Name : "+g)
}
